# Generated by Django 3.1.3 on 2020-12-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='rut',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
