# Generated by Django 3.1.3 on 2020-12-03 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20201203_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='partners.partner'),
        ),
    ]
