# Generated by Django 3.1.3 on 2020-12-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20201203_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount_paid',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='isVariable',
            field=models.BooleanField(null=True),
        ),
    ]
