# Generated by Django 3.1.3 on 2020-12-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20201204_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='isVariable',
            new_name='is_variable',
        ),
    ]
